### ISSUE TITLE
get_initial_spreadsheets does not correctly create enzyme_stoichiometries.xlsx file

### ISSUE THREAD

**Issue by diana-sz** [klamt-lab/autopacmen#11]
Hello! I just started using the package and I am trying to apply it to my model. But I noticed that the gene rules that I get in the "...enzyme_stoichiometries.xlsx" file are not interpreted correctly (they still contain some "and"). The problem seems to be the function **_gene_rule_as_list().**
I tested the function alone and it seems that it does not work with the example provided.
"(b0001 or b0002) and b0003" is returned as ['b0001', 'b0002 and b0003'] and not as [["b0001", "b0002"], "b0003"]

```
from typing import Any, Dict, List, Union

def _gene_rule_as_list(gene_rule: str) -> List[Any]:
    """Returns a given string gene rule in list form.

    I.e. (b0001 or b0002) and b0003 is returned as
    [["b0001", "b0002"], "b0003"]

    Arguments:
    *gene_rule: str ~ The gene rule which shall be converted into the list form.
    """
    # Gene rules: Only ) or (, (in blocks only and); No ) and (
    gene_rule_blocks = gene_rule.split(" ) or ( ")
    gene_rule_blocks = [x.replace("(", "").replace(")", "") for x in gene_rule_blocks]
    gene_rules_array: List[Union[str, List[str]]] = []
    for block in gene_rule_blocks:
        if " or " in block:
            block_list = block.split(" or ")
            block_list = [x.lstrip().rstrip() for x in block_list]
            gene_rules_array += block_list
        elif " and " in block:
            block_list = block.split(" and ")
            block_list = [x.lstrip().rstrip() for x in block_list]
            gene_rules_array.append(block_list)
        else:  # single enzyme
            gene_rules_array.append(block)
    return gene_rules_array

gene_rule = "(b0001 or b0002) and b0003"
_gene_rule_as_list(gene_rule)
```
This outputs:
`['b0001', 'b0002 and b0003']
`

I hope I did not accidentally mess something up :) I would appreciate any help with this. Thank you!

**Comment by Paulocracy** [comment]
Hello Diana!
First of all I'm very sorry about my inexcusable slow response! You actually did not mess anything up :-), this is an actual bug in _gene_rule_as_list and, with my lasted referenced commit, I think that it should be resolved now. Actually, the example that I gave was an invalid one (at least for cobrapy) as gene rules typically do not use or in parentheses, which added some confusion for me ^^ so that I changed the example given in the docstring.

**Comment by diana-sz** [comment]
Thank you for fixing it! :) 
The problem was also partially with my model. It sometimes has "or" in parentheses, sometimes "and" and sometimes it has very complicated nested rules :D But now I know what the correct format of the rules is, so I can edit them in my model :)
