### ISSUE TITLE
Reactions with isoenzymes are not split correctly if proteomics data is provided

### ISSUE THREAD

**Issue by diana-sz** [klamt-lab/autopacmen#12]
Hello :) 
I would like to integrate proteomics data. But it seems that the reactions that have isoenzymes are not split correctly. I saw it with my metabolic model, but also in the model provided here "iJO1366_sMOMENT_2019_06_25_GECKO_ANALOGON.xml". For example the reaction PFK is split into PFK_GPRSPLIT_1 and PFK_GPRSPLIT_2. Each reaction should have only one of the isoenzymes in the reactants but the reactions are identical and they contain both isoenzymes and also the protein_pool.

```
        <listOfReactants>
          <speciesReference species="M_atp_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_f6p_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_ENZYME_b3916" stoichiometry="3.77565590812736e-06" constant="true"/>
          <speciesReference species="M_ENZYME_b1723" stoichiometry="3.77565590812736e-06" constant="true"/>
          <speciesReference species="M_prot_pool" stoichiometry="0.000122541206209238" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="M_adp_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_fdp_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_h_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_armm_PFK" stoichiometry="1" constant="true"/>
        </listOfProducts>
```

I have been trying to figure out how to fix it and one problem I found is in the script **create_smoment_model_reaction_wise.py**.
The function `get_model_with_separated_measured_enzyme_reactions()` updates the objects `reaction_id_gene_rules_mapping` and `reaction_id_gene_rules_protein_stoichiometry_mapping` where I assume it creates new gene rules for these split reactions.
However, later in the script in the main loop, the string "\_GPRSPLIT\_" is removed from the `reaction_id` and then gene_rules are retrieved for the original reaction instead of the split reactions. 

Another problem seems to be that it always adds the protein_pool metabolite even if there is proteomics data available. I think this is because of the line 304 ` reaction.add_metabolites(metabolites)`. It is always run even if the reaction already contains the individual enzyme. Would it make sense to add a condition that if all proteomics data is available, this line would not be run? 

Thanks in advance :)

**Comment by Paulocracy** [comment]
See #27 :-)
