### ISSUE TITLE
Enzyme pool reported as mmol/gDW in print

### ISSUE THREAD

**Issue by emikar** [klamt-lab/autopacmen#13]
Hey!

When running the function "get_initial_spreadsheets_with_sbml" (I'm calling the script directly, as I want my pipeline fully automated), there's a somewhat confusing print towards the end:

`NOTE: project_name_protein_data.xlsx has as default value for the enzyme pool P 0.095 mmol/gDW.`

I was under the impression that the enzyme pool is given in g/gDW, and indeed that is what is reported in the resulting excel file, so I assume this is just a minor typo, and should therefore be an easy fix :)

Cheers!

**Comment by Paulocracy** [comment]
You're absolutely right, and - much too late - I just fixed the typo, thank you for finding it :-)
