### ISSUE TITLE
enzyme names ore not written correctly to stoichiometry excel sheet

### ISSUE THREAD

**Issue by voidsailor** [klamt-lab/autopacmen#15]
Hi @Paulocracy,

in the updated version of "autopacmen/submodules/get_initial_spreadsheets.py" single enzyme names are stored as lists and contain brackets inside the excel sheet.
This later on produces an Error, when trying to read single enzyme names.

**Comment by voidsailor** [comment]
#16

**Comment by Paulocracy** [comment]
The lists are parsed seperately in order to reflect " AND " rules. As far as I retested it, I couldn't reproduce any errors :3

**Comment by Paulocracy** [comment]
See #27, you were nearly right @voidsailor :D
