### ISSUE TITLE
Uniprot API change

### ISSUE THREAD

**Issue by yaccos** [klamt-lab/autopacmen#24]
From my understanding, Uniprot's web API has changed from the time autoPACMEN was created and I used it. For this reason the Uniprot ID -> Protein mass mapping no longer works (https://github.com/klamt-lab/autopacmen/blob/cb828391d4cbb17e50ba9752cc974d78775d836d/autopacmen/submodules/get_protein_mass_mapping.py#L116C8-L116C105). However, I one of my group members have come up with a suggested solution; this is: Replace 
```python
uniprot_query_url = f"https://www.uniprot.org/uniprot/?query={query}&format=tab&columns=id,mass"
```
with 
```python
uniprot_query_url = f"https://rest.uniprot.org/uniprotkb/search?query=accession:{query}&format=tsv&fields=accession,mass"
```
I have tested both approaches in the web browser and can confirm that the old query string does no longer work, whereas the newly suggested one does.

**Comment by Paulocracy** [comment]
Fixed thanks to @yaccos as per #25 :-)
