### ISSUE TITLE
Potential bug in k-cat lookup

### ISSUE THREAD

**Issue by yaccos** [klamt-lab/autopacmen#26]
I have noticed a some strange code related to lookup of k-cat values https://github.com/klamt-lab/autopacmen/blob/180e382abb8586af5dae66676d35a7442b2540f6/autopacmen/submodules/get_reactions_kcat_mapping.py#L64-L67

I believe this block of code is there in order to ensure that forward and backwards k-cat values are not mixed together. Note however that the same action is taken regardless of the truth value of `kcat_direction == searched_direction == "forward"`. I suggest that the code should have been

```python
  # Ensures that only kcat values for the same direction
  # is used
  if kcat_direction == searched_direction:
            max_kcats.append(max_kcat)
```
However, I ask you to double check this as I might be missing something.

**Comment by Paulocracy** [comment]
Thank you (once again :D) for submitting a helpful issue :-) The code you should be actually different, just as you proposed it, I vaguely remember that I changed it as I had some problems with the used kcat<->protein database, so it made sense at one point in iJO1366*'s creation but not anymore xD
