### ISSUE TITLE
Malformed enzyme stoichiometry spreadsheet

### ISSUE THREAD

**Issue by yaccos** [klamt-lab/autopacmen#27]
This an error which is related to issues #15 and #12. With the most recent versions of `autoPACMEN` and dependent packages, `get_initial_spreadsheets_with_sbml()` produces an enzyme stoichiometry spreadsheet which looks like this:

![autoPACMEN error](https://github.com/klamt-lab/autopacmen/assets/22662263/7c0d45fb-9b64-44b0-a522-bbc1ab9b4f4e)

As you can see, gene annotations which consist of zero or one genes are surrounded by brackets with quotes. This causes problems in `create_smoment_model_reaction_wise_with_sbml()` which does not recognize the brackets and quotes.  Previously, I used older package versions (I can't recall the exact numbers), I instead got the expected behavior which excludes reactions without annotations and writes annotations with a single gene without brackets and quotes. I assume this bug is caused by changes in either `autoPACMEN` or `xlsxwriter`, but I have not yet got time to investigate thoroughly.

**Comment by mretier** [comment]
I have the same issue. My generated Excel sheet has the same formatting issues and running `create_smoment_model_reaction_wise_with_sbml` the subroutine `reaction_id_gene_rules_protein_stoichiometry_mapping` throws a `Key error`

**Comment by Paulocracy** [comment]
Thank you both for mentioning this issue, it is now (after an extreme amount of time, sorry for that!) hopefully fixed :D
